### PR TITLE
Add max width to input text preview and truncate

### PR DESCRIPTION
**Pull request by abenerd**
image

### CODE REVIEW

**Review by brumm — COMMENTED** [review]
could we do this with w-full or something that won't use hardcoded widths?

**Comment by abenerd** [comment]
It would then look something like this even for text that is not the full width.
CleanShot 2021-11-22 at 12 18 23

**Comment by brumm** [comment]
when fixing this, i'd like to make sure that the search term will be as short as possible and as wide as the parent container, with a `p-2` of a gap of padding

maybe you could put the search term into a container that's pinned to the right size by something like `top-2 right-2 left-2`. inside the container would be the actual styled search term.

**Comment by abenerd** [comment]
The width is now only as it needs to be.

https://user-images.githubusercontent.com/7523903/142906817-43e4c5c3-820a-4dcc-a220-0a3e2c8206cf.mp4

**Comment by brumm** [comment]
closed by #2

**Pull request closed without merging**
